name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup locale
        run: |
          sudo locale-gen pl_PL
          sudo locale-gen pl_PL.UTF-8
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y locales
          sudo update-locale LANG=pl_PL.UTF-8

      - name: Build using node.ks
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build website
        run: |
          sudo locale-gen pl_PL
          sudo locale-gen pl_PL.UTF-8
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y locales
          sudo update-locale LANG=pl_PL.UTF-8
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          cname: www.duszanadloni.com
